export const oldTestament = [
  { Book: "Génesis", Chapters: "50", Key: "GEN" },
  { Book: "Éxodo", Chapters: "40", Key: "EXO" },
  { Book: "Levítico", Chapters: "27", Key: "LEV" },
  { Book: "Números", Chapters: "36", Key: "NUM" },
  { Book: "Deuteronomio", Chapters: "34", Key: "DEU" },
  { Book: "Josué", Chapters: "24", Key: "JOS" },
  { Book: "Jueces", Chapters: "21", Key: "JDG" },
  { Book: "Rut", Chapters: "4", Key: "RUT" },
  { Book: "1 Samuel", Chapters: "31", Key: "1SA" },
  { Book: "2 Samuel", Chapters: "24", Key: "2SA" },
  { Book: "1 Reyes", Chapters: "22", Key: "1KI" },
  { Book: "2 Reyes", Chapters: "25", Key: "2KI" },
  { Book: "1 Crónicas", Chapters: "29", Key: "1CH" },
  { Book: "2 Crónicas", Chapters: "36", Key: "2CH" },
  { Book: "Esdras", Chapters: "10", Key: "EZR" },
  { Book: "Nehemías", Chapters: "13", Key: "NEH" },
  { Book: "Tobit", Chapters: "14", Key: "TOB" },
  { Book: "Judit", Chapters: "16", Key: "JDT" },
  { Book: "Ester", Chapters: "16", Key: "EST" },
  { Book: "1 Macabeos", Chapters: "16", Key: "1MA" },
  { Book: "2 Macabeos", Chapters: "15", Key: "2MA" },
  { Book: "Job", Chapters: "42", Key: "JOB" },
  { Book: "Salmos", Chapters: "150", Key: "PSA" },
  { Book: "Proverbios", Chapters: "31", Key: "PRO" },
  { Book: "Eclesiastés", Chapters: "12", Key: "ECC" },
  { Book: "Cantares", Chapters: "8", Key: "SNG" },
  { Book: "Sabiduría", Chapters: "19", Key: "WIS" },
  { Book: "Sirácide", Chapters: "51", Key: "SIR" },
  { Book: "Isaías", Chapters: "66", Key: "ISA" },
  { Book: "Jeremías", Chapters: "52", Key: "JER" },
  { Book: "Lamentaciones", Chapters: "5", Key: "LAM" },
  { Book: "Baruc", Chapters: "6", Key: "BAR" },
  { Book: "Ezequiel", Chapters: "48", Key: "EZK" },
  { Book: "Daniel", Chapters: "14", Key: "DAN" },
  { Book: "Oseas", Chapters: "14", Key: "HOS" },
  { Book: "Joel", Chapters: "3", Key: "JOL" },
  { Book: "Amós", Chapters: "9", Key: "AMO" },
  { Book: "Abdías", Chapters: "1", Key: "OBA" },
  { Book: "Jonás", Chapters: "4", Key: "JON" },
  { Book: "Miqueas", Chapters: "7", Key: "MIC" },
  { Book: "Nahum", Chapters: "3", Key: "NAM" },
  { Book: "Habacuc", Chapters: "3", Key: "HAB" },
  { Book: "Sofonías", Chapters: "3", Key: "ZEP" },
  { Book: "Hageo", Chapters: "2", Key: "HAG" },
  { Book: "Zacarías", Chapters: "14", Key: "ZEC" },
  { Book: "Malaquías", Chapters: "4", Key: "MAL" },
];

export const newTestament = [
  { Book: "Mateo", Chapters: "28", Key: "MAT" },
  { Book: "Marcos", Chapters: "16", Key: "MRK" },
  { Book: "Lucas", Chapters: "24", Key: "LUK" },
  { Book: "Juan", Chapters: "21", Key: "JHN" },
  { Book: "Hechos", Chapters: "28", Key: "ACT" },
  { Book: "Romanos", Chapters: "16", Key: "ROM" },
  { Book: "1 Corintios", Chapters: "16", Key: "1CO" },
  { Book: "2 Corintios", Chapters: "13", Key: "2CO" },
  { Book: "Gálatas", Chapters: "6", Key: "GAL" },
  { Book: "Efesios", Chapters: "6", Key: "EPH" },
  { Book: "Filipenses", Chapters: "4", Key: "PHP" },
  { Book: "Colosenses", Chapters: "4", Key: "COL" },
  { Book: "1 Tesalonicenses", Chapters: "5", Key: "1TH" },
  { Book: "2 Tesalonicenses", Chapters: "3", Key: "2TH" },
  { Book: "1 Timoteo", Chapters: "6", Key: "1TI" },
  { Book: "2 Timoteo", Chapters: "4", Key: "2TI" },
  { Book: "Tito", Chapters: "3", Key: "TIT" },
  { Book: "Filemón", Chapters: "1", Key: "PHM" },
  { Book: "Hebreos", Chapters: "13", Key: "HEB" },
  { Book: "Santiago", Chapters: "5", Key: "JAS" },
  { Book: "1 Pedro", Chapters: "5", Key: "1PE" },
  { Book: "2 Pedro", Chapters: "3", Key: "2PE" },
  { Book: "1 Juan", Chapters: "5", Key: "1JN" },
  { Book: "2 Juan", Chapters: "1", Key: "2JN" },
  { Book: "3 Juan", Chapters: "1", Key: "3JN" },
  { Book: "Judas", Chapters: "1", Key: "JUD" },
  { Book: "Apocalipsis", Chapters: "22", Key: "REV" },
];
